### ISSUE TITLE
Sidemenu background imageview layout gap

### ISSUE THREAD

**Issue by zhiranchen** [lemberg/connfa-ios#15]
I face an issue when I tried to change the sidemenu background image. 
The background image for sidebar menu seems to leave a gap at the top. 
I created the background image following the UI guide and it has a dimension of 1042*2208px.
I tested on an iPhone 6plus  and an iPhone 5s simulators and the results are the same. 
<img width="313" alt="screen shot 2018-04-27 at 5 47 05 pm" src="https://user-images.githubusercontent.com/22383558/39389980-14769658-4a43-11e8-9119-632d9bc276b7.png">
I tried to debug but cannot fix it. Please let me know if you have the same issue.

**Comment by ivancwh** [comment]
Hi @zhiranchen, I was facing this issue too but I have an alternative option.

Please go to Storyboards > Main.storyboard > Side Menu View Controller 

Check on the "background" top constraint. Please remove the top constraint and set a new top constraint pointing to "View" with 0 instead of "Top Layout Guide".

I think previously they were concerning on the status bar so they left the spacing by setting top constraint to "Top Layout Guide" (It is a good standard to point to "Top Layout Guide"). Just in case if you want to colour your status bar with other colour instead of merging with the side menu background.

**Pictures Guidance**

Step 1 :
![screen shot 2018-07-10 at 4 25 13 pm](https://user-images.githubusercontent.com/35020880/42498270-47d6d54e-845e-11e8-9ea7-e5a911510cb6.png)

Step 2 :
![screen shot 2018-07-10 at 4 25 47 pm](https://user-images.githubusercontent.com/35020880/42498323-735cc2fa-845e-11e8-99f8-fcbb48d4f2fd.png)

Step 3 :
![screen shot 2018-07-10 at 4 26 00 pm](https://user-images.githubusercontent.com/35020880/42498334-7a90f6cc-845e-11e8-84f1-4cd48058dbe1.png)

Step 4 :
![screen shot 2018-07-10 at 4 26 09 pm](https://user-images.githubusercontent.com/35020880/42498341-81b7f946-845e-11e8-8421-adfec6d6def6.png)

**Comment by edgarmirandasilva** [comment]
Thank you @ivancwh

**Comment by zhiranchen** [comment]
Thank you! @ivancwh
